CREATE DATABASE db_employ;


USE db_employ;



CREATE TABLE DEPT(
DEPTNO  INT PRIMARY KEY  NOT NULL ,
DNAME VARCHAR(100)NOT NULL UNIQUE,
LOC VARCHAR (100)NOT NULL,
);


CREATE TABLE EMP(
EMPON INT PRIMARY KEY,
Ename  VARCHAR (100) NOT NULL,
JOB VARCHAR(200) NOT NULL,
MGR INT,

HIREDATE DATE NOT NULL,
sal INT NOT NULL ,
comm INT NOT NULL ,
DEPTNO INT,
FOREIGN KEY (MGR) REFERENCES EMP(EMPON),
FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)

);

CREATE TABLE SALGRADE(
GRADE INT IDENTITY(1,1),
LOSAL INT NOT NULL UNIQUE,
HISAL INT NOT NULL UNIQUE,
);


CREATE TABLE JOB_HISTORY(

EMPNO INT IDENTITY(1,1),
JOB VARCHAR(100),
START_DATE DATE,
END_DATE DATE,
CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (EMPNO, START_DATE),
FOREIGN KEY (EMPNO) REFERENCES EMP(EMPON),
)



drop table DEPT